/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Usuario;
import java.awt.BorderLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author ConoMaster
 */
public class FramePrincipal extends javax.swing.JFrame {

    private static Usuario user;
    boolean inicioSesion = false;
    private PanelUsuario panelIngreso;
    private PanelInicial panelInicial;
    public PanelUsuarioIniciado panelUsuarioIniciado;
    public PanelUsuarioResumen panelUsuarioResumen;
    public VistaDetalle vistaDetalle;
    public JDialogAutores jDialogAutores;
    
    
    public FramePrincipal() {
        initComponents();
        
        menuAcerca.setEnabled(false);
        menuVisualizar.setEnabled(false);
        itemSalir.setEnabled(false);

        
        
        panelIngreso = new PanelUsuario(this);
        panelInicial = new PanelInicial();
        panelUsuarioResumen = new PanelUsuarioResumen();
        
        
        
        this.setResizable(false);
        this.setLayout(new BorderLayout());
        cambiarPanel(panelInicial);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuValidar = new javax.swing.JMenu();
        itemEntrar = new javax.swing.JMenuItem();
        itemSalir = new javax.swing.JMenuItem();
        menuVisualizar = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        itemResumen = new javax.swing.JMenuItem();
        menuAcerca = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuValidar.setText("Validar");

        itemEntrar.setText("Entrar");
        itemEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEntrarActionPerformed(evt);
            }
        });
        menuValidar.add(itemEntrar);

        itemSalir.setText("Salir");
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        menuValidar.add(itemSalir);

        jMenuBar1.add(menuValidar);

        menuVisualizar.setText("Visualizar");

        jMenuItem2.setText("Detalle");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuVisualizar.add(jMenuItem2);

        itemResumen.setText("Resumen");
        itemResumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemResumenActionPerformed(evt);
            }
        });
        menuVisualizar.add(itemResumen);

        jMenuBar1.add(menuVisualizar);

        menuAcerca.setText("Acerca de");
        menuAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAcercaActionPerformed(evt);
            }
        });

        jMenuItem3.setText("Acerca de");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuAcerca.add(jMenuItem3);

        jMenuBar1.add(menuAcerca);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEntrarActionPerformed

       panelIngreso = new PanelUsuario(this);
       this.cambiarPanel(panelIngreso);
   
    }//GEN-LAST:event_itemEntrarActionPerformed

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        
        panelUsuarioIniciado.setVisible(false);
        
        this.setSize(650, 648);
        panelInicial = new PanelInicial();
        cambiarPanel(panelInicial);
        panelInicial.setVisible(true);
        
        itemEntrar.setVisible(true);
        itemSalir.setEnabled(false);
        menuAcerca.setEnabled(false);
        menuVisualizar.setEnabled(false);
    }//GEN-LAST:event_itemSalirActionPerformed

    private void itemResumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemResumenActionPerformed
        panelUsuarioResumen = new PanelUsuarioResumen(user);
        
        this.cambiarPanel(panelUsuarioResumen);
        
    }//GEN-LAST:event_itemResumenActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try {
            vistaDetalle = new VistaDetalle(user);
            this.cambiarPanel(vistaDetalle);
        } catch (SQLException ex) {
            Logger.getLogger(FramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menuAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAcercaActionPerformed
        
    }//GEN-LAST:event_menuAcercaActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       jDialogAutores = new JDialogAutores(this, true);
        jDialogAutores.setVisible(true);
        this.pack();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }
    
    
//    private void cambiarPanel(javax.swing.JPanel panel)
//    {
//        this.setContentPane(panel);
//        this.pack();
//    }
    
    void cambiarPanel(javax.swing.JPanel panel) 
    {
        // Eliminar todos los componentes existentes en el marco
        this.getContentPane().removeAll();

        // Establecer el nuevo panel en el contenido del marco
        this.setContentPane(panel);

        // Revalidar y repintar el marco para reflejar los cambios
        this.revalidate();
        this.repaint();

        // Ajustar el tamaño del marco según el nuevo panel
        this.pack();
    }

    public static Usuario getUser() {
        return user;
    }

    public static void setUser(Usuario user) {
        FramePrincipal.user = user;
    }

    public boolean isInicioSesion() {
        return inicioSesion;
    }

    public void setInicioSesion(boolean inicioSesion) {
        this.inicioSesion = inicioSesion;
    }

    public PanelUsuario getPanelIngreso() {
        return panelIngreso;
    }

    public void setPanelIngreso(PanelUsuario panelIngreso) {
        this.panelIngreso = panelIngreso;
    }

    public PanelInicial getPanelInicial() {
        return panelInicial;
    }

    public void setPanelInicial(PanelInicial panelInicial) {
        this.panelInicial = panelInicial;
    }

    public PanelUsuarioIniciado getPanelUsuarioIniciado() {
        return panelUsuarioIniciado;
    }

    public void setPanelUsuarioIniciado(PanelUsuarioIniciado panelUsuarioIniciado) {
        this.panelUsuarioIniciado = panelUsuarioIniciado;
    }

    public JMenuItem getItemEntrar() {
        return itemEntrar;
    }

    public void setItemEntrar(JMenuItem itemEntrar) {
        this.itemEntrar = itemEntrar;
    }

    public JMenuItem getItemSalir() {
        return itemSalir;
    }

    public void setItemSalir(JMenuItem itemSalir) {
        this.itemSalir = itemSalir;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    public JMenuItem getjMenuItem1() {
        return jMenuItem1;
    }

    public void setjMenuItem1(JMenuItem jMenuItem1) {
        this.jMenuItem1 = jMenuItem1;
    }

    public JMenu getMenuAcerca() {
        return menuAcerca;
    }

    public void setMenuAcerca(JMenu menuAcerca) {
        this.menuAcerca = menuAcerca;
    }

    public JMenu getMenuValidar() {
        return menuValidar;
    }

    public void setMenuValidar(JMenu menuValidar) {
        this.menuValidar = menuValidar;
    }

    public JMenu getMenuVisualizar() {
        return menuVisualizar;
    }

    public void setMenuVisualizar(JMenu menuVisualizar) {
        this.menuVisualizar = menuVisualizar;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem itemEntrar;
    private javax.swing.JMenuItem itemResumen;
    public javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    public javax.swing.JMenu menuAcerca;
    private javax.swing.JMenu menuValidar;
    public javax.swing.JMenu menuVisualizar;
    // End of variables declaration//GEN-END:variables

    
}
