version: '3.8'  
services:  
  db:  
    container_name: pg_container  
    image: postgres  
    restart: always  
    environment:  
      POSTGRES_USER: pablo  
      POSTGRES_PASSWORD: pablo  
      POSTGRES_DB: practica6  
    ports:  
      - "5432:5432"  
