package Model;
// Generated 20-feb-2024 13:46:17 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int id;
     private String nombreUsuario;
     private String contrasena;
     private String correoElectronico;
     private Date fechaIngreso;
     private String fotografia;
     private Double precioTotal;

    public Usuario() {
    }

	
    public Usuario(int id) {
        this.id = id;
    }
    public Usuario(int id, String nombreUsuario, String contrasena, String correoElectronico, Date fechaIngreso, String fotografia, Double precioTotal) {
       this.id = id;
       this.nombreUsuario = nombreUsuario;
       this.contrasena = contrasena;
       this.correoElectronico = correoElectronico;
       this.fechaIngreso = fechaIngreso;
       this.fotografia = fotografia;
       this.precioTotal = precioTotal;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public String getFotografia() {
        return this.fotografia;
    }
    
    public void setFotografia(String fotografia) {
        this.fotografia = fotografia;
    }

    public Double getPrecioTotal() {
        return precioTotal;
    }

    public void setPrecioTotal(Double precioTotal) {
        this.precioTotal = precioTotal;
    }

    @Override
    public String toString() {
        return "Usuario{" + "id=" + id + ", nombreUsuario=" + nombreUsuario + ", contrasena=" + contrasena + ", correoElectronico=" + correoElectronico + ", fechaIngreso=" + fechaIngreso + ", fotografia=" + fotografia + ", precioTotal=" + precioTotal + '}';
    }

}


