/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ConsultaManga;
import Controlador.ConsultaOperaciones;
import Controlador.MError;
import Controlador.MiExcepcion;
import Controlador.Utilidad;
import Modelo.CompraBD;
import Modelo.Manga;
import Modelo.MangaDB;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author ConoMaster
 */
public class PanelBotones extends javax.swing.JPanel {

    /**
     * Creates new form PanelBotones
     */
    PanelManga panelManga;
    PanelListaMangas panelCarrito;
    Manga manga = new Manga();
    
    ConsultaManga consulta = new ConsultaManga();
    MangaDB m = new MangaDB(consulta.getRs());
    ConsultaOperaciones operaciones = new ConsultaOperaciones();
    CompraBD compras = new CompraBD(operaciones.operacionSelectGeneral("SELECT * FROM COMPRA WHERE USUNIF = '" + FramePrincipal.usuarioPrincipal.getNif() + "'"));
    
    public PanelBotones(PanelManga panelManga, PanelListaMangas panelCarrito) throws SQLException {
        initComponents();
        this.panelManga = panelManga;
        this.panelCarrito = panelCarrito;
        botonAtras.setEnabled(false);
        manga = consulta.inicial();
        mostrarDatos();
        System.out.println(manga);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonSiguiente = new javax.swing.JButton();
        botonAtras = new javax.swing.JButton();
        botonAñadirCarrito = new javax.swing.JButton();
        botonPrimero = new javax.swing.JButton();
        botonUltimo = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 153));

        botonSiguiente.setText("SIGUIENTE");
        botonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguienteActionPerformed(evt);
            }
        });

        botonAtras.setText("ANTERIOR");
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });

        botonAñadirCarrito.setText("AÑADIR AL CARRITO");
        botonAñadirCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadirCarritoActionPerformed(evt);
            }
        });

        botonPrimero.setText("PRIMERO");
        botonPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPrimeroActionPerformed(evt);
            }
        });

        botonUltimo.setText("ULTIMO");
        botonUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUltimoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(botonPrimero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonAtras, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(botonAñadirCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonUltimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAñadirCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonPrimero, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(botonUltimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiguienteActionPerformed
        
        botonAtras.setEnabled(true);
        try {
            manga = consulta.siguiente();
            if(consulta.isLast()){
                botonSiguiente.setEnabled(false);
            }
        } catch (SQLException ex) {
            Logger.getLogger(PanelBotones.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        mostrarDatos();
    }//GEN-LAST:event_botonSiguienteActionPerformed

    private void botonAñadirCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadirCarritoActionPerformed
       int confirmar = JOptionPane.showConfirmDialog(this,"¿Desea añadir este manga al carrito?");
       if(confirmar == 0){
           compras = new CompraBD(operaciones.operacionSelectGeneral("SELECT * FROM COMPRA WHERE USUNIF = '" + FramePrincipal.usuarioPrincipal.getNif() + "'"));
           if(compras.comprobarExistencias(manga.getId())){
               try {
                   //Controlo la actualización, si el resultado es distinto de -1 significa que se ha añadido correctamente, si no saltará la excepcion porque
                   //Se han añadido mas del numero limite
                   int resultado = operaciones.updateTablaCompra(confirmar, manga.getId(), FramePrincipal.getUsuarioPrincipal().getNif(), Utilidad.obtenerFechaActual());
                   if(resultado != -1){
                       JOptionPane.showMessageDialog(this, "¡Añadido al carrito con éxito!");
                   }
               } catch (MiExcepcion ex) {
                   JOptionPane.showMessageDialog(this, MError.getMensaje(ex.getCodigo()));
                   MError.CreadorLog(MError.getMensaje(ex.getCodigo()));
               }
           }else{
               //Si no hay existencias en la tabla compra de ese producto, creará uno nuevo añadiendo la cantidad a 1
               operaciones.operacionInsert("INSERT INTO COMPRA (USUNIF, MANID, FECHACOMPRA, CANTIDAD) VALUES ('" + FramePrincipal.usuarioPrincipal.getNif() + "', " + manga.getId() + ", '" + Utilidad.obtenerFechaActual() + "', " + 1 + ")");
           }
           
       }
    }//GEN-LAST:event_botonAñadirCarritoActionPerformed

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed

        botonSiguiente.setEnabled(true);
        try {
            manga = consulta.atras();
            if(consulta.isFirst()){
                botonAtras.setEnabled(false);
            }
        } catch (SQLException ex) {
            Logger.getLogger(PanelBotones.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        mostrarDatos();
    }//GEN-LAST:event_botonAtrasActionPerformed

    private void botonPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPrimeroActionPerformed
    botonSiguiente.setEnabled(true);
    botonAtras.setEnabled(false);
        try {
            manga = consulta.inicial();
        } catch (SQLException ex) {
            Logger.getLogger(PanelBotones.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    mostrarDatos();
    }//GEN-LAST:event_botonPrimeroActionPerformed

    private void botonUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUltimoActionPerformed
    
        botonSiguiente.setEnabled(false);
        botonAtras.setEnabled(true);
        try {
            manga = consulta.ultimo();
        } catch (SQLException ex) {
            Logger.getLogger(PanelBotones.class.getName()).log(Level.SEVERE, null, ex);
        }

        mostrarDatos();
    }//GEN-LAST:event_botonUltimoActionPerformed


    public void mostrarDatos(){
        panelManga.getFotoManga().setIcon(Utilidad.obtenerIconoPorNombre(manga.getFoto(), "C:\\Users\\ConoMaster\\Documents\\NetBeansProjects\\Proyectos Netbeans8.2\\Proyecto6\\src\\Imagen"));
        panelManga.getTituloField().setText(manga.getNombreManga());
        panelManga.getDescripcionField().setText(manga.getDescripcion());
        panelManga.getPrecioField().setText("" + manga.getPrecio() + " €");
    }

    public Manga getManga() {
        return manga;
    }

    public void setManga(Manga manga) {
        this.manga = manga;
    }

    public PanelManga getPanelManga() {
        return panelManga;
    }

    public void setPanelManga(PanelManga panelManga) {
        this.panelManga = panelManga;
    }

    public PanelListaMangas getPanelCarrito() {
        return panelCarrito;
    }

    public void setPanelCarrito(PanelListaMangas panelCarrito) {
        this.panelCarrito = panelCarrito;
    }

    public ConsultaManga getConsulta() {
        return consulta;
    }

    public void setConsulta(ConsultaManga consulta) {
        this.consulta = consulta;
    }

    public MangaDB getM() {
        return m;
    }

    public void setM(MangaDB m) {
        this.m = m;
    }

    public ConsultaOperaciones getOperaciones() {
        return operaciones;
    }

    public void setOperaciones(ConsultaOperaciones operaciones) {
        this.operaciones = operaciones;
    }

    public CompraBD getCompras() {
        return compras;
    }

    public void setCompras(CompraBD compras) {
        this.compras = compras;
    }

    public JButton getBotonAtras() {
        return botonAtras;
    }

    public void setBotonAtras(JButton botonAtras) {
        this.botonAtras = botonAtras;
    }

    public JButton getBotonAñadirCarrito() {
        return botonAñadirCarrito;
    }

    public void setBotonAñadirCarrito(JButton botonAñadirCarrito) {
        this.botonAñadirCarrito = botonAñadirCarrito;
    }

    public JButton getBotonPrimero() {
        return botonPrimero;
    }

    public void setBotonPrimero(JButton botonPrimero) {
        this.botonPrimero = botonPrimero;
    }

    public JButton getBotonSiguiente() {
        return botonSiguiente;
    }

    public void setBotonSiguiente(JButton botonSiguiente) {
        this.botonSiguiente = botonSiguiente;
    }

    public JButton getBotonUltimo() {
        return botonUltimo;
    }

    public void setBotonUltimo(JButton botonUltimo) {
        this.botonUltimo = botonUltimo;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtras;
    private javax.swing.JButton botonAñadirCarrito;
    private javax.swing.JButton botonPrimero;
    private javax.swing.JButton botonSiguiente;
    private javax.swing.JButton botonUltimo;
    // End of variables declaration//GEN-END:variables
}
