/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ConsultaOperaciones;
import Controlador.MError;
import Controlador.MiExcepcion;
import Modelo.Compra;
import Modelo.CompraBD;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ConoMaster
 */
public class PanelHistorial extends javax.swing.JPanel {

    /**
     * Creates new form PanelFactura
     */
    ConsultaOperaciones control = new ConsultaOperaciones();
    DefaultTableModel modelo;
    CompraBD compraBD = new CompraBD(control.operacionSelectGeneral("SELECT * FROM COMPRA WHERE USUNIF = '" + FramePrincipal.usuarioPrincipal.getNif() + "'"));

    public PanelHistorial() {
        initComponents();
        modelo = rellenarTabla();
        tablaFacturas.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaFacturas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        botonEliminar = new javax.swing.JButton();

        tablaFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaFacturas);

        jLabel1.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Historial compras");

        botonEliminar.setText("ELIMINAR REGISTRO");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 305, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
    
        if (tablaFacturas.getSelectedRow() != -1) {
            if (JOptionPane.showConfirmDialog(this, "¿Desea eliminar ese registro?") == 0) {
                Object objeto = tablaFacturas.getModel().getValueAt(tablaFacturas.getSelectedRow(), 2);
                System.out.println(objeto);                
                control.operacionBorrarElementoCompra(FramePrincipal.usuarioPrincipal.getNif(), (int)objeto);
                JOptionPane.showMessageDialog(this, "Registro eliminado con éxito");
                modelo.removeRow(tablaFacturas.getSelectedRow());
            }
        }
        
        
    }//GEN-LAST:event_botonEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaFacturas;
    // End of variables declaration//GEN-END:variables

    public DefaultTableModel rellenarTabla() {
    ArrayList<Compra> compras = compraBD.getCompras();

    // Nombres de las columnas
    String[] columnNames = {"ID Factura", "NIF Usuario", "ID Manga", "Fecha de Compra", "Cantidad"};

    // Crear el modelo con nombres de columnas y 0 filas
    DefaultTableModel model = new DefaultTableModel(columnNames, 0);

    for (Compra compra : compras) {
        // Agregar una fila al modelo para cada compra
        Object[] rowData = {compra.getIdFactura(), compra.getNifUsuario(), compra.getIdManga(), compra.getFechaCompra().getTime().toInstant().atZone(ZoneId.systemDefault()).toLocalDate(), compra.getCantidad()};
        model.addRow(rowData);
    }

    return model;
}
}
