/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ConexionBD;
import Controlador.MiExcepcion;
import Controlador.ConsultaValidacion;
import Modelo.UsuarioBD;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ConoMaster
 */
public class PanelInicioSesion extends javax.swing.JPanel {

    /**
     * Creates new form PanelInicioSesion
     */
    FramePrincipal frame;
    public PanelInicioSesion(FramePrincipal frame) {
        initComponents();
        this.frame = frame;
        
        //Le añado funcionalidad al checkbox para mostrar contraseña
        checkMostrarContrasenia.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    // Mostrar la contraseña
                    contraseniaField.setEchoChar((char) 0);
                } else {
                    // Ocultar la contraseña
                    contraseniaField.setEchoChar('*');
                }
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        usuarioField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        contraseniaField = new javax.swing.JPasswordField();
        botonEntrar = new javax.swing.JButton();
        botonAtras = new javax.swing.JButton();
        checkMostrarContrasenia = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        jLabel1.setText("Usuario");

        usuarioField.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        jLabel2.setText("Contraseña");

        contraseniaField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        botonEntrar.setText("ENTRAR");
        botonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEntrarActionPerformed(evt);
            }
        });

        botonAtras.setText("ATRAS");

        checkMostrarContrasenia.setText("Mostrar Contraseña");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(checkMostrarContrasenia))
                        .addComponent(usuarioField)
                        .addComponent(contraseniaField, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(botonEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(184, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(usuarioField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(checkMostrarContrasenia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contraseniaField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 305, Short.MAX_VALUE)
                .addComponent(botonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEntrarActionPerformed
        
        /*try {
            ConexionBD.abrir();
        } catch (MiExcepcion ex) {
            Logger.getLogger(PanelInicioSesion.class.getName()).log(Level.SEVERE, null, ex);
        }
        UsuarioBD usuario = new UsuarioBD("where NOMBRE_USUARIO = '" + usuarioField.getText() + "' and CONTRASENIA = '" + contraseniaField.getText()+"'");
         */
        ConsultaValidacion val = new ConsultaValidacion();

        if (!val.validarUsuario(usuarioField.getText(), contraseniaField.getText())) {
            JOptionPane.showMessageDialog(null, "No existe este usuario en la base de datos");
        } else {
            UsuarioBD usuario = new UsuarioBD(val.getRs());
            try {
                FramePrincipal.usuarioPrincipal = usuario.getUsuario();
                System.out.println(usuario.getUsuario());
                System.out.println(FramePrincipal.usuarioPrincipal);
                frame.getBotonIngresar().setEnabled(false);
                frame.getBotonRegistro().setEnabled(false);
                frame.getBotonSalir().setEnabled(true);
                frame.getBotonHerramientas().setVisible(true);
                frame.getBotonHerramientas().setEnabled(true);
                usuario.cerrar();
                val.close();
            } catch (MiExcepcion ex) {
                Logger.getLogger(PanelInicioSesion.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

        
        if(frame.usuarioPrincipal != null){
            this.setVisible(false);
            frame.setContentPane(frame.panelPrincipal);
            frame.pack();
        }
    }//GEN-LAST:event_botonEntrarActionPerformed

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtras;
    private javax.swing.JButton botonEntrar;
    private javax.swing.JCheckBox checkMostrarContrasenia;
    private javax.swing.JPasswordField contraseniaField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField usuarioField;
    // End of variables declaration//GEN-END:variables

    


}
