/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ConsultaOperaciones;
import Controlador.MError;
import Controlador.MiExcepcion;
import Controlador.Utilidad;
import Modelo.Usuario;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import static java.nio.file.StandardCopyOption.REPLACE_EXISTING;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author ConoMaster
 */
public class PanelUsuario extends javax.swing.JPanel {

    /**
     * Creates new form PanelUsuario
     */
    Usuario user;
    String rutaFoto;
    public PanelUsuario(Usuario user) {
        initComponents();
        this.user = user;
        rutaFoto = user.getFoto();
        mostrarElementos();
        activarDesactivarModificacion(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fotoUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonModificar = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        nifField = new javax.swing.JTextField();
        nombreField = new javax.swing.JTextField();
        nombreUsuarioField = new javax.swing.JTextField();
        botonCambiarImagen = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NIF");

        jLabel2.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nombre de usuario");

        botonModificar.setText("MODIFICAR");
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });

        botonAceptar.setText("ACEPTAR");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonCancelar.setText("CANCELAR");

        nifField.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        nifField.setForeground(new java.awt.Color(255, 0, 0));
        nifField.setText("jTextField1");

        nombreField.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        nombreField.setForeground(new java.awt.Color(255, 0, 0));
        nombreField.setText("jTextField1");

        nombreUsuarioField.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        nombreUsuarioField.setForeground(new java.awt.Color(255, 0, 0));
        nombreUsuarioField.setText("jTextField1");

        botonCambiarImagen.setText("Cambiar imagen");
        botonCambiarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCambiarImagenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(fotoUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nifField)
                            .addComponent(nombreField)
                            .addComponent(nombreUsuarioField, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(botonCambiarImagen)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 260, Short.MAX_VALUE)
                .addComponent(botonCancelar)
                .addGap(18, 18, 18)
                .addComponent(botonModificar)
                .addGap(18, 18, 18)
                .addComponent(botonAceptar)
                .addGap(262, 262, 262))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(botonCambiarImagen)
                .addGap(18, 18, 18)
                .addComponent(fotoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nifField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(nombreUsuarioField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonModificar)
                    .addComponent(botonCancelar)
                    .addComponent(botonAceptar))
                .addGap(111, 111, 111))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed
    activarDesactivarModificacion(true);
    nifField.setEditable(false);
    
    }//GEN-LAST:event_botonModificarActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        Usuario nuevoUsuario = null;
        if(!nombreField.getText().isEmpty() && !nombreUsuarioField.getText().isEmpty()){
            try {
                nuevoUsuario = new Usuario(nifField.getText(), nombreUsuarioField.getText(), user.getContrasenia(), nombreField.getText(), rutaFoto);
                
            } catch (MiExcepcion ex) {
                JOptionPane.showMessageDialog(this, MError.getMensaje(ex.getCodigo()));
                mostrarElementos();
                activarDesactivarModificacion(false);
            }
            System.out.println(nuevoUsuario);
        if(nuevoUsuario != null){
            ConsultaOperaciones operaciones = new ConsultaOperaciones();
            operaciones.operacionModificarUsuario(nuevoUsuario, user.getNif());
            JOptionPane.showMessageDialog(this, "Usuario actualizado con exito!");
            FramePrincipal.usuarioPrincipal = nuevoUsuario;
            activarDesactivarModificacion(false);
        }
            
            
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonCambiarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCambiarImagenActionPerformed
    
        rutaFoto = seleccionarFoto();
        fotoUsuario.setIcon(Utilidad.obtenerIconoPorNombre(rutaFoto, "C:\\Users\\ConoMaster\\Documents\\NetBeansProjects\\Proyectos Netbeans8.2\\Proyecto6\\src\\Imagen\\"));
    }//GEN-LAST:event_botonCambiarImagenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCambiarImagen;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonModificar;
    private javax.swing.JLabel fotoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nifField;
    private javax.swing.JTextField nombreField;
    private javax.swing.JTextField nombreUsuarioField;
    // End of variables declaration//GEN-END:variables


    
    private void mostrarElementos(){
        nifField.setText(FramePrincipal.usuarioPrincipal.getNif());
        nombreField.setText(FramePrincipal.usuarioPrincipal.getNombre());
        nombreUsuarioField.setText(FramePrincipal.usuarioPrincipal.getUsuario());
        fotoUsuario.setIcon(Utilidad.obtenerIconoPorNombre(FramePrincipal.usuarioPrincipal.getFoto(), "C:\\Users\\ConoMaster\\Documents\\NetBeansProjects\\Proyectos Netbeans8.2\\Proyecto6\\src\\Imagen"));
    }
    
    private void activarDesactivarModificacion(boolean b){
        botonCambiarImagen.setVisible(b);
        botonCancelar.setVisible(b);
        botonAceptar.setVisible(b);
        nifField.setEditable(b);
        nombreField.setEditable(b);
        nombreUsuarioField.setEditable(b);
        botonModificar.setVisible(!b);
    }
    
    private String seleccionarFoto() {

        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de Imagen (.jpg)", "jpg");
        fileChooser.setFileFilter(filter);
        int resultado = fileChooser.showOpenDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            

            try {
                // Crear la carpeta "Imagenes" si no existe
                File archivoSeleccionado = fileChooser.getSelectedFile();
                String nombreArchivo = archivoSeleccionado.getName();

                // Obtener el directorio del proyecto
                String destino = System.getProperty("user.dir") + "\\src\\Imagen\\" + nombreArchivo;
                System.out.println(destino);
                Path destinoRuta = Paths.get(destino);

                String Orig = archivoSeleccionado.getPath();
                Path origen = Paths.get(Orig);

                Files.copy(origen, destinoRuta, REPLACE_EXISTING);
                return nombreArchivo;
            } catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error al copiar la imagen", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        } else {
            return "default.jpg";
        }
        return null;
    }

}
